babamul:
  webapp_url: https://babamul.caltech.edu
  oauth:
    redirect_base_url: https://babamul.caltech.edu/api

gpu:
  device_ids: [0]

kafka:
  producer:
    server: "broker:29092"

workers:
  ztf:
    alert:
      n_workers: 8
    enrichment:
      n_workers: 12
      batch_size: 1000
    filter:
      n_workers: 4
  lsst:
    alert:
      n_workers: 10
    enrichment:
      n_workers: 10
    filter:
      n_workers: 4
  decam:
    alert:
      n_workers: 1
    enrichment:
      n_workers: 1
    filter:
      n_workers: 1