/**
 * Fallback ZTF Avro schema for offline/testing use.
 * Contains the most commonly used ZTF candidate fields.
 * This is used when the BOOM API schema endpoint is unreachable.
 */

export const ZTF_FALLBACK_SCHEMA = {
  type: "record",
  name: "ZtfAlertToFilter",
  fields: [
    { name: "candid", type: "long" },
    { name: "objectId", type: "string" },
    {
      name: "candidate",
      type: {
        type: "record",
        name: "ZtfCandidate",
        fields: [
          { name: "jd", type: "double" },
          { name: "fid", type: "int" },
          { name: "pid", type: "long" },
          { name: "diffmaglim", type: ["null", "float"] },
          { name: "programid", type: "int" },
          { name: "candid", type: "long" },
          { name: "isdiffpos", type: "string" },
          { name: "nid", type: ["null", "int"] },
          { name: "distnr", type: ["null", "float"] },
          { name: "magnr", type: ["null", "float"] },
          { name: "sigmagnr", type: ["null", "float"] },
          { name: "chinr", type: ["null", "float"] },
          { name: "sharpnr", type: ["null", "float"] },
          { name: "ra", type: "double" },
          { name: "dec", type: "double" },
          { name: "magpsf", type: "float" },
          { name: "sigmapsf", type: "float" },
          { name: "chipsf", type: ["null", "float"] },
          { name: "magap", type: ["null", "float"] },
          { name: "sigmagap", type: ["null", "float"] },
          { name: "sky", type: ["null", "float"] },
          { name: "magdiff", type: ["null", "float"] },
          { name: "fwhm", type: ["null", "float"] },
          { name: "classtar", type: ["null", "float"] },
          { name: "mindtoedge", type: ["null", "float"] },
          { name: "ssdistnr", type: ["null", "float"] },
          { name: "ssmagnr", type: ["null", "float"] },
          { name: "rb", type: ["null", "float"] },
          { name: "drb", type: ["null", "float"] },
          { name: "ndethist", type: "int" },
          { name: "ncovhist", type: "int" },
          { name: "jdstarthist", type: ["null", "double"] },
          { name: "jdendhist", type: ["null", "double"] },
          { name: "scorr", type: ["null", "double"] },
          { name: "toession", type: ["null", "long"] },
          { name: "objectidps1", type: ["null", "long"] },
          { name: "objectidps2", type: ["null", "long"] },
          { name: "objectidps3", type: ["null", "long"] },
          { name: "sgmag1", type: ["null", "float"] },
          { name: "srmag1", type: ["null", "float"] },
          { name: "simag1", type: ["null", "float"] },
          { name: "szmag1", type: ["null", "float"] },
          { name: "sgscore1", type: ["null", "float"] },
          { name: "distpsnr1", type: ["null", "float"] },
          { name: "sgmag2", type: ["null", "float"] },
          { name: "srmag2", type: ["null", "float"] },
          { name: "simag2", type: ["null", "float"] },
          { name: "szmag2", type: ["null", "float"] },
          { name: "sgscore2", type: ["null", "float"] },
          { name: "distpsnr2", type: ["null", "float"] },
          { name: "sgmag3", type: ["null", "float"] },
          { name: "srmag3", type: ["null", "float"] },
          { name: "simag3", type: ["null", "float"] },
          { name: "szmag3", type: ["null", "float"] },
          { name: "sgscore3", type: ["null", "float"] },
          { name: "distpsnr3", type: ["null", "float"] },
          { name: "nmtchps", type: "int" },
          { name: "clrcoeff", type: ["null", "float"] },
          { name: "clrcounc", type: ["null", "float"] },
          { name: "neargaia", type: ["null", "float"] },
          { name: "neargaiabright", type: ["null", "float"] },
          { name: "maggaia", type: ["null", "float"] },
          { name: "maggaiabright", type: ["null", "float"] },
        ],
      },
    },
    {
      name: "coordinates",
      type: {
        type: "record",
        name: "GalacticCoordinates",
        fields: [
          { name: "l", type: "double" },
          { name: "b", type: "double" },
        ],
      },
    },
    {
      name: "classifications",
      type: {
        type: "record",
        name: "ZtfAlertClassifications",
        fields: [
          { name: "acai_h", type: ["null", "float"] },
          { name: "acai_v", type: ["null", "float"] },
          { name: "acai_o", type: ["null", "float"] },
          { name: "acai_n", type: ["null", "float"] },
          { name: "acai_b", type: ["null", "float"] },
          { name: "btsbot", type: ["null", "float"] },
        ],
      },
    },
    {
      name: "properties",
      type: {
        type: "record",
        name: "ZtfAlertProperties",
        fields: [
          { name: "rock", type: "boolean" },
          { name: "star", type: "boolean" },
          { name: "near_brightstar", type: "boolean" },
          { name: "stationary", type: "boolean" },
        ],
      },
    },
  ],
};
